### ISSUE TITLE
Could you give some advices for photography beginners?

### ISSUE THREAD

**Issue by sinout** [sapegin/ama#10]
Hi, Artem @sapegin !
First of all thank you for react-styleguidist. It was a real pleasure using it in our development.

I know that you're a great photographer :)
I've seen your photos on Unsplash and they are really amazing.

I'm a fan of landscape/street/architecture photography, so I learned a bit about shutter speed, ISO, aperture and bought my first DSLR camera. But I feel I am lacking in knowledge and skills to start.

Could you share some advices/books/resources that helped you at the beginning ? 
What resources/books do you recommend to read about photo post-processing ?

Thanks in advance!

**Comment by sapegin** [comment]
![](http://morning.photos/photos/large/2017-11-01-1866-large.jpg)

Hey Taras, thanks for your question!

It will be hard to recommend some book because most of photography books I’ve read are out of print now, but I’ll try.

Shooting:

* [Within the Frame: The Journey of Photographic Vision](https://www.amazon.com/Within-Frame-Journey-Photographic-Vision/dp/0134288629/?tag=artesapesphot-20) by David duChemin
* [Digital Nature Photography: The Art and the Science](https://www.amazon.com/Digital-Nature-Photography-Art-Science/dp/0415742420/?tag=artesapesphot-20) by John and Barbara Gerlach
* [Mastering Photographic Composition, Creativity, and Personal Style](https://www.amazon.com/Mastering-Photographic-Composition-Creativity-Personal/dp/1933952229/?tag=artesapesphot-20) by Alain Briot

Editing:

* [Vision & Voice: Refining Your Vision in Adobe Photoshop Lightroom](https://www.amazon.com/gp/product/0321670094/?tag=artesapesphot-20) by David duChemin 
* [Photographically Speaking: A Deeper Look at Creating Stronger Images](https://www.amazon.com/Photographically-Speaking-Deeper-Creating-Stronger/dp/0321750446/?tag=artesapesphot-20) by David duChemin
* [The Landscape Photographer’s Guide to Photoshop: A Visualization-Driven Workflow](https://www.amazon.com/Landscape-Photographers-Guide-Photoshop-Visualization-Driven/dp/1681982188/?tag=artesapesphot-20) by Guy Tal

More:

* [Yevgen Timashov’s ebooks](http://www.fotolandscape.com/learn/category/e-books/) (in Russian)
* [Mitchell Kanashkevich’s ebooks](https://www.mitchellk-photos.com/travel-photography-resource)
* [Bruce Percy’s ebooks](http://www.brucepercy.co.uk/e-books-technique/)

And some short advice: shoot more, show less (much less than you think), and don’t go to popular sections of photography sites like 500px ;—)

P. S. Would be super cool if the readers could recommend more in comments. And feel free to ask more questions about photography.

**Comment by sinout** [comment]
@sapegin , that's huge. Thank you.
