### ISSUE TITLE
What's the Berlin tech scene like?

### ISSUE THREAD

**Issue by vernondegoede** [sapegin/ama#14]
Hi!

Our company is about to expand to Europe, and will open a new office in Berlin. What do you think of the tech scene in Berlin? I read on some blogs that there aren't a lot of tech startups, but that the number of interesting startups / scaleups is growing. Do you agree? How do you get in touch with other software developers outside of works?

Vernon

**Comment by sapegin** [comment]
Hey Vernon! Thanks for the question!

I don’t know much about startups, because I’m not going to work for any of them ;-) But it feels like Berlin has more work for developers than any other European city, and the salaries are one of the most reasonable comparing to the cost of living.

I get in touch with other developers mostly using Twitter. I also go occasionally to meetups (there are many of them in Berlin!) or conferences (mostly outside of Berlin and Germany though).

**Comment by vernondegoede** [comment]
Thanks for your answer! Let's grab a coffee when I'm in Berlin ☕️
