### ISSUE TITLE
How do you study English and what can you recommend?

### ISSUE THREAD

**Issue by HZ-labs** [sapegin/ama#4]
books, courses, apps, methods ...?

**Comment by sapegin** [comment]
Hey @HZ-labs, thanks for the question! 

It was very long trip and I still have a lot to learn ;-)

First I just started to use English as much (or as little at that time) as I could. For example:

* Switch UI of all apps from Russian to English.
* Read docs and tech articles in English instead of their Russian translations.
* Read tech books.
* Watch conference talks‘ videos.
* [Tweet in English](https://twitter.com/iamsapegin).
* Write [blog](http://blog.sapegin.me/).
* Read fiction books.

But the most efficient were lessons with a native speaker. I had them three times a week for almost three years that I was working at Badoo, and my group was so small and lazy that most of the time I had one-to-one lessons ;-) That’s amazing to help you start actually speaking: when your teacher speaks very poor Russian you just have to speak English and explain things you don’t know with the words you already know. That’s very useful.

I hope it will be useful ;-)

**Comment by mxstbr** [comment]
I've met @sapegin in person and his english is A+, so this is definitely good advice 💯

**Comment by sapegin** [comment]
@mxstbr Thanks for kind words! 😊

**Comment by HZ-labs** [comment]
Thanks a lot for your answer! :thumbsup:
