### ISSUE TITLE
Which books do you recommend to read?

### ISSUE THREAD

**Issue by vitkarpov** [sapegin/ama#5]
Hey, Artem!

Do you have a list of books which you'd recommend to read?

**Comment by sapegin** [comment]
Hey Viktor, thanks for your question!

According to our Facebook discussion it supposed to be a list of easy to read books in English — books written in a simple non-scholarly language and suitable for beginners. [The original post](http://bizikov.ru/posts/100-design-books/) was about design books but since I’m a developer there are books for developers too (in no particular order):

* [Don’t Make Me Think: A Common Sense Approach to Web Usability](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515/?tag=artesapesphot-20) by Steve Krug
* [The Inmates Are Running the Asylum: Why High Tech Products Drive Us Crazy and How to Restore the Sanity](https://www.amazon.com/Inmates-Are-Running-Asylum-Products-ebook/dp/B000OZ0N62/?tag=artesapesphot-20) by Alan Cooper
* [Design for Hackers: Reverse Engineering Beauty](https://www.amazon.com/Design-Hackers-Reverse-Engineering-Beauty-ebook/dp/B005J578EW/?tag=artesapesphot-20) by David Kadavy
* [Getting Real: The Smarter, Faster, Easier Way to Build a Successful Web Application](https://gettingreal.37signals.com/) by 37signals
* [Rework](https://37signals.com/rework) by 37signals
* [The Good Creative: 18 ways to make better art](https://www.amazon.com/gp/product/B00KNL65LO/?tag=artesapesphot-20) by Paul Jarvis
* [Effective Programming: More Than Writing Code](https://www.amazon.com/gp/product/B008HUMTO0/?tag=artesapesphot-20) by Jeff Atwood
* [The Art of Readable Code](https://www.amazon.com/gp/product/0596802293/?tag=artesapesphot-20) by Dustin Boswell and Trevor Foucher
* [Open Source Guides](https://opensource.guide/) by GitHub
* [The Tao of Pooh](https://www.amazon.com/gp/product/0140067477/?tag=artesapesphot-20) by Benjamin Hoff
* [A book apart](https://abookapart.com/) books
* [Five simple steps](https://www.fivesimplesteps.com/blogs/news/115270533-some-of-our-books-live-on) books

I hope readers would recommend more. Leave a comment below!
